name: Run RuboCop

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.7' ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Run RuboCop
        run: |
          cp Gemfile.local Gemfile
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
